name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - dev_keyur

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code from the main branch
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3" # You can specify the version or use 'latest'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build the Flutter web app
      - name: Build Flutter web app
        run: flutter build web --release

      # Fix the <base href> in index.html
      - name: Update <base href> in index.html
        run: |
          sed -i 's|<base href="/">|<base href="./">|g' build/web/index.html

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
